name: tekartik_bootstrap_asset
description: Bootstrap for dart
version: 3.3.7
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  tekartik_jquery_asset:
    git:
      url: git://github.com/tekartik/jquery_asset.dart
      ref: dart2
    version: '>=3.1.1+1'
#dependency_overrides:
#  tekartik_jquery_asset:
#    path: ../tekartik_jquery_asset.dart